server:
  port: 8090

#datasource (oracle)
spring:
  datasource:
    driverClassNname: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: oracle1234

#mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true





    #logging:
    #   level:
    #      root: debug

